
import com.mongodb.BasicDBList;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frmAdminUpdate extends javax.swing.JFrame {

    /**
     * Creates new form frmAdminUpdate
     */
    public frmAdminUpdate() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPackage = new javax.swing.JTable();
        btnDisplay = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblPackid = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblPackName = new javax.swing.JLabel();
        txtPackName = new javax.swing.JTextField();
        lblChannels = new javax.swing.JLabel();
        txtPackCost = new javax.swing.JTextField();
        lblPackCost = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblChannels = new javax.swing.JTable();
        lblChnl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Package");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tblPackage.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblPackage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pack ID", "Pack Name", "Channels", "Pack Cost"
            }
        ));
        tblPackage.setIntercellSpacing(new java.awt.Dimension(10, 1));
        tblPackage.setRowHeight(25);
        tblPackage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPackageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPackage);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(760, 160, 530, 188);

        btnDisplay.setBackground(new java.awt.Color(102, 153, 255));
        btnDisplay.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnDisplay.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay);
        btnDisplay.setBounds(770, 550, 90, 30);

        btnUpdate.setBackground(new java.awt.Color(102, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(980, 550, 90, 30);

        lblPackid.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblPackid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPackid.setText("Pack ID :");
        getContentPane().add(lblPackid);
        lblPackid.setBounds(200, 140, 150, 30);

        lblid.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblid.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblid);
        lblid.setBounds(400, 140, 260, 30);

        lblPackName.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblPackName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPackName.setText("Pack Name :");
        getContentPane().add(lblPackName);
        lblPackName.setBounds(190, 210, 150, 30);

        txtPackName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtPackName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtPackName);
        txtPackName.setBounds(400, 210, 260, 30);

        lblChannels.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblChannels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChannels.setText("Channels :");
        getContentPane().add(lblChannels);
        lblChannels.setBounds(190, 350, 150, 30);

        txtPackCost.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtPackCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPackCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPackCostActionPerformed(evt);
            }
        });
        txtPackCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPackCostKeyPressed(evt);
            }
        });
        getContentPane().add(txtPackCost);
        txtPackCost.setBounds(400, 280, 260, 30);

        lblPackCost.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblPackCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPackCost.setText("Pack Cost :");
        getContentPane().add(lblPackCost);
        lblPackCost.setBounds(190, 280, 150, 30);

        btnDelete.setBackground(new java.awt.Color(102, 153, 255));
        btnDelete.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(1190, 550, 90, 30);

        tblChannels.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblChannels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Channels"
            }
        ));
        tblChannels.setIntercellSpacing(new java.awt.Dimension(10, 1));
        tblChannels.setRowHeight(25);
        tblChannels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChannelsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblChannels);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(400, 440, 170, 184);

        lblChnl.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblChnl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblChnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblChnl);
        lblChnl.setBounds(400, 350, 260, 30);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select New Channels :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 440, 260, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\delete (1).png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1170, 440, 120, 110);

        lblWelcome1.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome1.setText("update  packages");
        getContentPane().add(lblWelcome1);
        lblWelcome1.setBounds(400, 30, 510, 47);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\homegif (3).gif")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 40, 80, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\database_search (2).png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(770, 430, 100, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\updated (1).jpg")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(980, 440, 90, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\url.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1380, 770);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\homegif (3).gif")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 50, 80, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void display()
    {
        try{
        
        Connection j = new Connection();
        DBCollection dbc = j.connection("Package");
        
        String[] colNames = {"Pid","Package Name ","Channels","Pack Cost"};
        DefaultTableModel dtm = new DefaultTableModel(colNames,0);
        DBCursor cursor = dbc.find();
       
        String c1 = "";
        
        while(cursor.hasNext())
        {
            DBObject obj = cursor.next();
            String pid = (String)obj.get("Pid");
            String pname = (String)obj.get("Pack_name");
            BasicDBObject bdb = new BasicDBObject();
            bdb.put("Pid",pid);
            DBCursor cursor1 = dbc.find(bdb);
            while(cursor1.hasNext())
            {
                c1 = cursor1.next().get("Channels").toString();
            }
            String cost = (String)obj.get("Pack_cost");
            
            dtm.addRow(new Object[]{pid,pname,c1,cost});
            tblPackage.setModel(dtm);
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    
    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        
        display();
    }//GEN-LAST:event_btnDisplayActionPerformed

    public void update()
    {
        int x = tblChannels.getSelectedRow();
        System.out.println(x);
        
        if(txtPackName.getText().equals("") || txtPackCost.getText().equals("") || (x==-1 && lblChnl.getText().equals("")))
        {
            final JOptionPane jo = new JOptionPane();
            JOptionPane.showMessageDialog(jo,"Please fill all the fields!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
         
        Connection c = new Connection();
        DBCollection dbc = c.connection("Package");
        BasicDBObject bdb = new BasicDBObject();
        BasicDBObject search = new BasicDBObject();
        search.put("Pid",lblid.getText());
        
        String[] colNames = {"Pid","Package Name","Channels","Package Cost"};
        DefaultTableModel dtm = new DefaultTableModel(colNames,0);
        
        DefaultTableModel dtm1 = (DefaultTableModel) tblChannels.getModel();

        int s = tblChannels.getSelectedRowCount();
                
        int[] ab = tblChannels.getSelectedRows();
               
        BasicDBList bdl = new BasicDBList();
        for(int i = 0; i<s;i++)
        {
            bdl.add(tblChannels.getValueAt(ab[i],0).toString());
        }
        
        bdb.put("Pid", lblid.getText());
        bdb.put("Pack_name",txtPackName.getText());
        
        if(x==-1)
        {
            bdb.put("Channels",lblChnl.getText());
        }
        else
            bdb.put("Channels", bdl);
     
        bdb.put("Pack_cost",txtPackCost.getText());

        
        dbc.update(search,bdb);
        tblPackage.setModel(dtm);
        tblPackage.repaint();
        tblChannels.repaint();
        dtm1.fireTableDataChanged();
        
        lblid.setText("");
        lblChnl.setText("");
        txtPackCost.setText("");
        txtPackName.setText("");
        
    }
    
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblPackageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPackageMouseClicked
      
        int r = tblPackage.getSelectedRow();
        lblid.setText(tblPackage.getModel().getValueAt(r,0).toString());
        txtPackName.setText(tblPackage.getModel().getValueAt(r,1).toString());
        lblChnl.setText(tblPackage.getModel().getValueAt(r,2).toString());
        txtPackCost.setText(tblPackage.getModel().getValueAt(r,3).toString());
    }//GEN-LAST:event_tblPackageMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
        Connection j = new Connection();
        DBCollection dbc = j.connection("Package");
        String[] colNames = {"Pack ID","Package Name","Channels","Pack Cost"};
        DefaultTableModel dtm = new DefaultTableModel(colNames,0);
        
        DBCursor cursor = dbc.find();
        
        String c1  = "";
               
        while(cursor.hasNext())
        {
            DBObject obj = cursor.next();
            String pid = (String)obj.get("Pid");
            String pname = (String)obj.get("Pack_name");
            String cost = (String)obj.get("Pack_cost");
            
            BasicDBObject bdb = new BasicDBObject();
            bdb.put("Pid",pid);
            DBCursor cursor1 = dbc.find(bdb);
            int i = 0;
            while(cursor1.hasNext())
            {
                c1 = cursor1.next().get("Channels").toString();
            }
            dtm.addRow(new Object[]{pid,pname,c1,cost});
            tblPackage.setModel(dtm);
        }
        
        DBCollection dbc1 = j.connection("Channels");
        
        String[] colNames1 = {"Channels"};
        DefaultTableModel dtm1 = new DefaultTableModel(colNames1,0);
        DBCursor cursor1 = dbc1.find();
        
        while(cursor1.hasNext())
        {
            DBObject obj1 = cursor1.next();
            String name = (String)obj1.get("Cname");
            dtm1.addRow(new Object[]{name});
            tblChannels.setModel(dtm1);
        }
        
        lblChnl.setText(null);
        txtPackName.setText(null);
        txtPackCost.setText(null);
        lblid.setText(null);
    }//GEN-LAST:event_formWindowActivated

    public void delete()
    {
        Connection c = new Connection();
            DBCollection dbc = c.connection("Package");

            int i = tblPackage.getSelectedRow();
            
            if(i==-1)
            {
                final JOptionPane jo = new JOptionPane();
                JOptionPane.showMessageDialog(jo,"No Row selected!!!","Error",JOptionPane.ERROR_MESSAGE);
            }

            
            JDialog.setDefaultLookAndFeelDecorated(true);
            int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirm",
                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.YES_OPTION)
            {   
                String id = tblPackage.getValueAt(i,0).toString();

                BasicDBObject document = new BasicDBObject();
                document.put("Pid",id);
                dbc.remove(document);

                final JOptionPane jo = new JOptionPane();
                JOptionPane.showMessageDialog(jo,"Package Deleted!!!","Success",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(true);
            } 
            else if (response == JOptionPane.NO_OPTION) 
            {   
            }        
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtPackCostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPackCostKeyPressed
        
        final KeyEvent k=evt;
        txtPackCost.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e) 
            {
                  final char c=k.getKeyChar();
                  if(Character.isLetter(c) || (Character.isWhitespace(c)))
                  {
                      txtPackCost.setEditable(false);
                  }
                  else
                  {
                      txtPackCost.setEditable(true);
                  }  
            }
        });  
    }//GEN-LAST:event_txtPackCostKeyPressed

    private void tblChannelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChannelsMouseClicked
        
        lblChnl.setText("");
    }//GEN-LAST:event_tblChannelsMouseClicked

    private void txtPackCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPackCostActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        new frmAdminOption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        display();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        
        update();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        delete();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        new frmAdminOption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
       
    }//GEN-LAST:event_jLabel5MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdminUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblChannels;
    private javax.swing.JLabel lblChnl;
    private javax.swing.JLabel lblPackCost;
    private javax.swing.JLabel lblPackName;
    private javax.swing.JLabel lblPackid;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTable tblChannels;
    private javax.swing.JTable tblPackage;
    private javax.swing.JTextField txtPackCost;
    private javax.swing.JTextField txtPackName;
    // End of variables declaration//GEN-END:variables
}
