
import com.mongodb.BasicDBList;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class frmAdminInsert extends javax.swing.JFrame {
    
    public frmAdminInsert() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPackid = new javax.swing.JTextField();
        txtPackName = new javax.swing.JTextField();
        txtPackCost = new javax.swing.JTextField();
        lblPackid = new javax.swing.JLabel();
        lblPackName = new javax.swing.JLabel();
        lblChannels = new javax.swing.JLabel();
        lblPackCost = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblChannels = new javax.swing.JTable();
        lblWelcome1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insert Package");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        txtPackid.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtPackid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPackid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPackidKeyPressed(evt);
            }
        });
        getContentPane().add(txtPackid);
        txtPackid.setBounds(440, 180, 150, 30);

        txtPackName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtPackName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPackName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPackNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtPackName);
        txtPackName.setBounds(440, 280, 150, 30);

        txtPackCost.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtPackCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPackCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPackCostActionPerformed(evt);
            }
        });
        txtPackCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPackCostKeyPressed(evt);
            }
        });
        getContentPane().add(txtPackCost);
        txtPackCost.setBounds(440, 380, 150, 30);

        lblPackid.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblPackid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPackid.setText("Pack ID :");
        getContentPane().add(lblPackid);
        lblPackid.setBounds(220, 180, 150, 30);

        lblPackName.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblPackName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPackName.setText("Pack Name :");
        getContentPane().add(lblPackName);
        lblPackName.setBounds(220, 280, 150, 30);

        lblChannels.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblChannels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChannels.setText("Channels :");
        getContentPane().add(lblChannels);
        lblChannels.setBounds(740, 170, 150, 30);

        lblPackCost.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblPackCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPackCost.setText("Pack Cost :");
        getContentPane().add(lblPackCost);
        lblPackCost.setBounds(220, 380, 150, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\homegif (3).gif")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 60, 80, 80);

        tblChannels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Channels"
            }
        ));
        tblChannels.setIntercellSpacing(new java.awt.Dimension(10, 1));
        tblChannels.setRowHeight(25);
        jScrollPane4.setViewportView(tblChannels);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(990, 170, 119, 184);

        lblWelcome1.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome1.setText("INSERT  packages");
        getContentPane().add(lblWelcome1);
        lblWelcome1.setBounds(440, 50, 510, 47);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 60, 80, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\clear (3).png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(660, 470, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\insert (1).jpg")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(960, 470, 90, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\url.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1400, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insert()
    {
        int x = tblChannels.getRowCount();
        if(txtPackid.getText().equals("") || txtPackName.getText().equals("") || txtPackCost.getText().equals("") || x==-1)
        {
            final JOptionPane jo = new JOptionPane();
            JOptionPane.showMessageDialog(jo,"Please fill all the fields!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Connection j = new Connection();
            DBCollection dbc = j.connection("Package");
            BasicDBObject bdb = new BasicDBObject();
            
            String abc = "";
            bdb.put("Pid", txtPackid.getText());
            DBCursor cursor = dbc.find(bdb);
            while(cursor.hasNext())
            {
                DBObject obj = cursor.next();
                abc = (String)obj.get("Pid");  
            }
            
            if(abc!="")
            {
                final JOptionPane jo = new JOptionPane();
                JOptionPane.showMessageDialog(jo,"Pack ID already exists!!!","Error",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                int s = tblChannels.getSelectedRowCount();

                int[] ab = tblChannels.getSelectedRows();

                BasicDBList bdl = new BasicDBList();
                for(int i = 0; i<s;i++)
                {
                    bdl.add(tblChannels.getValueAt(ab[i],0).toString());
                }

                DBObject document = new BasicDBObject("Pid",txtPackid.getText())
                .append("Pack_name", txtPackName.getText())
                .append("Channels", bdl)
                .append("Pack_cost", txtPackCost.getText());

                dbc.insert(document);

                final JPanel p2 = new JPanel();
                final JOptionPane jo = new JOptionPane();

                JOptionPane.showMessageDialog(p2,"Inserted!!!","Success",JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new  frmAdminOption().setVisible(true);
            }
        }
    }
    
    private void txtPackNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPackNameActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        Connection c = new Connection();
        DBCollection dbc = c.connection("Channels");
        
        String[] colNames = {"Channels"};
        DefaultTableModel dtm = new DefaultTableModel(colNames,0);
        DBCursor cursor = dbc.find();
        
        while(cursor.hasNext())
        {
            DBObject obj = cursor.next();
            String cname = (String)obj.get("Cname");
            dtm.addRow(new Object[]{cname});
            tblChannels.setModel(dtm);
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtPackidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPackidKeyPressed
                     
        final KeyEvent k=evt;
        txtPackid.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e) 
            {
                  final char c=k.getKeyChar();
                  if(Character.isLetter(c) || (Character.isWhitespace(c)))
                  {
                      txtPackid.setEditable(false);
                  }
                  else
                  {
                      txtPackid.setEditable(true);
                  }  
            }
        });  
    }//GEN-LAST:event_txtPackidKeyPressed

    private void txtPackCostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPackCostKeyPressed
        
        final KeyEvent k=evt;
        txtPackCost.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e) 
            {
                  final char c=k.getKeyChar();
                  if(Character.isLetter(c) || (Character.isWhitespace(c)))
                  {
                      txtPackCost.setEditable(false);
                  }
                  else
                  {
                      txtPackCost.setEditable(true);
                  }  
            }
        });  
    }//GEN-LAST:event_txtPackCostKeyPressed

    private void txtPackCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackCostActionPerformed
        
        insert();
    }//GEN-LAST:event_txtPackCostActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       
        txtPackid.setText(null);
        txtPackName.setText(null);
        txtPackCost.setText(null);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        insert();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        new frmAdminOption().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdminInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdminInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblChannels;
    private javax.swing.JLabel lblPackCost;
    private javax.swing.JLabel lblPackName;
    private javax.swing.JLabel lblPackid;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JTable tblChannels;
    private javax.swing.JTextField txtPackCost;
    private javax.swing.JTextField txtPackName;
    private javax.swing.JTextField txtPackid;
    // End of variables declaration//GEN-END:variables
}
