
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;


public class frmBill extends javax.swing.JFrame {

    /**
     * Creates new form frmBill
     */
    String id = "";
    public frmBill(String cid) {
        initComponents();
        id = cid;
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFinalBill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tblFinalBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bill ID :", null},
                {"Customer ID :", null},
                {"Customer Name :", null},
                {"Total Cost Of Packages", null},
                {"Date Of Subscription :", null}
            },
            new String [] {
                "", ""
            }
        ));
        tblFinalBill.setIntercellSpacing(new java.awt.Dimension(30, 1));
        tblFinalBill.setPreferredSize(new java.awt.Dimension(100, 250));
        tblFinalBill.setRowHeight(50);
        jScrollPane1.setViewportView(tblFinalBill);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 200, 377, 272);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\print (1).png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(690, 310, 100, 90);

        lblWelcome1.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome1.setText("Bill");
        getContentPane().add(lblWelcome1);
        lblWelcome1.setBounds(480, 40, 270, 47);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\pdf.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(940, 310, 110, 110);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\mail (1).png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1170, 300, 90, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\download--3-.jpg")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1040, 70, 150, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\url.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1390, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        Connection c = new Connection();
        DBCollection dbc = c.connection("pcust");
        DBCollection dbc1 = c.connection("cust");
        
        BasicDBObject Query = new BasicDBObject();
        Query.put("Custid", id);
        DBCursor cursor = dbc1.find(Query);
        String a = "";
        String d = "";
        
        while(cursor.hasNext()) 
        {
            DBObject obj = cursor.next();
            a = (String)obj.get("Name");
            d = (String) obj.get("Date_subs");
        }
        
        BasicDBObject Query1 = new BasicDBObject();
        Query.put("Custid", id);
        DBCursor cursor1 = dbc.find(Query1);
        String b = "";
        
        while(cursor1.hasNext()) {
            
            DBObject obj = cursor1.next();
            b = (String)obj.get("Pack_cost");
        }
        
        Random r = new Random();

        int  n = r.nextInt(100000) + 100;
        
        tblFinalBill.setValueAt(n, 0, 1);
        tblFinalBill.setValueAt(id, 1, 1);
        tblFinalBill.setValueAt(a, 2, 1);
        tblFinalBill.setValueAt(b+"/-", 3, 1);
        tblFinalBill.setValueAt(d, 4, 1);
    }//GEN-LAST:event_formWindowActivated

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        MessageFormat header=new MessageFormat("Bill Details");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        try{
             tblFinalBill.print(JTable.PrintMode.NORMAL,header,footer);
        
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("Cannot Print %%n", e.getMessage());
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        Document doc = new Document();
         try {
            try {            
                PdfWriter.getInstance(doc, new FileOutputStream("Bill.pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frmBill.class.getName()).log(Level.SEVERE, null, ex);
            }
            } 
            
          catch (DocumentException ex) {
             Logger.getLogger(frmBill.class.getName()).log(Level.SEVERE, null, ex);
         }
            doc.open();
            tblFinalBill.setTableHeader(null);

            PdfPTable pdfTable = new PdfPTable(tblFinalBill.getColumnCount());

            for (int i = 0; i < tblFinalBill.getColumnCount(); i++) {
                pdfTable.addCell(tblFinalBill.getColumnName(i));
            }
            
            for (int rows = 0; rows < tblFinalBill.getRowCount(); rows++) {
                for (int cols = 0; cols < tblFinalBill.getColumnCount(); cols++) {
                    pdfTable.addCell(tblFinalBill.getModel().getValueAt(rows, cols).toString());
                }
            }
         try {
             doc.add(pdfTable);
         } catch (DocumentException ex) {
             Logger.getLogger(frmBill.class.getName()).log(Level.SEVERE, null, ex);
         }
            doc.close();
         try {
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\Bill.pdf");
         } catch (IOException ex) {
             Logger.getLogger(frmBill.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        frmEmail e = new frmEmail();
        e.mail();
        this.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        new frmChoose().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JTable tblFinalBill;
    // End of variables declaration//GEN-END:variables
}
