
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class frmChoose extends javax.swing.JFrame {

    /**
     * Creates new form frmChoose
     */
    String id = "";
    public frmChoose() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCustid = new javax.swing.JTextField();
        lblForget = new javax.swing.JLabel();
        lblNew = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblOld = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblFrame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setBackground(new java.awt.Color(255, 153, 153));
        setBounds(new java.awt.Rectangle(0, 0, 350, 400));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setForeground(new java.awt.Color(204, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        txtCustid.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        txtCustid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustidActionPerformed(evt);
            }
        });
        getContentPane().add(txtCustid);
        txtCustid.setBounds(550, 200, 230, 40);

        lblForget.setBackground(new java.awt.Color(204, 255, 255));
        lblForget.setFont(new java.awt.Font("Colonna MT", 1, 24)); // NOI18N
        lblForget.setForeground(new java.awt.Color(51, 102, 255));
        lblForget.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForget.setText("Forgot ID");
        lblForget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgetMouseClicked(evt);
            }
        });
        getContentPane().add(lblForget);
        lblForget.setBounds(620, 360, 130, 30);

        lblNew.setBackground(new java.awt.Color(204, 255, 255));
        lblNew.setFont(new java.awt.Font("Colonna MT", 1, 30)); // NOI18N
        lblNew.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNew.setText("Create New Account");
        getContentPane().add(lblNew);
        lblNew.setBounds(1000, 210, 310, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\download--2- (1).jpg")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(840, 510, 150, 50);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(922, 180, 2, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\login (3).png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 300, 190, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\register1 (1).png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1050, 300, 210, 80);

        lblOld.setBackground(new java.awt.Color(204, 255, 255));
        lblOld.setFont(new java.awt.Font("Colonna MT", 1, 28)); // NOI18N
        lblOld.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOld.setText("Customer ID :");
        getContentPane().add(lblOld);
        lblOld.setBounds(280, 200, 210, 40);

        lblWelcome.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome  to  this  site!!!");
        getContentPane().add(lblWelcome);
        lblWelcome.setBounds(540, 60, 500, 47);

        lblFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/url.jpg"))); // NOI18N
        getContentPane().add(lblFrame);
        lblFrame.setBounds(0, 0, 1370, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void login()
    {
        id = txtCustid.getText();
        if(id.equals(""))
        {
            final JOptionPane jo = new JOptionPane();
            JOptionPane.showMessageDialog(jo,"Please enter your ID!!!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String a = "";
        
        Connection c = new Connection();
        DBCollection dbc = c.connection("cust");
        
        BasicDBObject Query = new BasicDBObject();
        Query.put("Custid", id);
        DBCursor cursor = dbc.find(Query);
        
        while(cursor.hasNext()) {
            
            DBObject obj = cursor.next();
            a = (String)obj.get("Custid");
        }
        
        final JPanel p1 = new JPanel();
        final JOptionPane jo = new JOptionPane();
        
        if(a.toString().equals(id))
        {
            this.setVisible(false);
            new frmDetails(a).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(p1,"Invalid ID","login error",JOptionPane.ERROR_MESSAGE);
            txtCustid.setText("");
        }
    }
    
    private void txtCustidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustidActionPerformed

        login();
    }//GEN-LAST:event_txtCustidActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
         login();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        frmRegister fr = new frmRegister();
        fr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
         System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lblForgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgetMouseClicked
        
        new frmGetID().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblForgetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblForget;
    private javax.swing.JLabel lblFrame;
    private javax.swing.JLabel lblNew;
    private javax.swing.JLabel lblOld;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtCustid;
    // End of variables declaration//GEN-END:variables
}
