
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aishwariya
 */
public class frmDisplay extends javax.swing.JFrame {

    
    String id = "";
        
    public frmDisplay(Vector v) {
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);            
        
        lbli.setText((String) v.elementAt(0));
        lbln.setText((String) v.elementAt(1));
        lblp.setText((String) v.elementAt(2));
        lblg.setText((String) v.elementAt(3));
        lble.setText((String) v.elementAt(4));
        lbla.setText((String) v.elementAt(5));
        lbld.setText((String) v.elementAt(6));

        
    }

    private frmDisplay() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblPno = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblDos = new javax.swing.JLabel();
        lbln = new javax.swing.JLabel();
        lblp = new javax.swing.JLabel();
        lblg = new javax.swing.JLabel();
        lbla = new javax.swing.JLabel();
        lble = new javax.swing.JLabel();
        lbld = new javax.swing.JLabel();
        lblCustid = new javax.swing.JLabel();
        lbli = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirm Info");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        lblName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name :");
        getContentPane().add(lblName);
        lblName.setBounds(200, 290, 150, 35);

        lblPno.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblPno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPno.setText("Phone no :");
        getContentPane().add(lblPno);
        lblPno.setBounds(830, 300, 150, 35);

        lblGender.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGender.setText("Gender :");
        getContentPane().add(lblGender);
        lblGender.setBounds(200, 370, 150, 35);

        lblEmail.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email :");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(200, 450, 150, 35);

        lblAddress.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress.setText("Address :");
        getContentPane().add(lblAddress);
        lblAddress.setBounds(830, 390, 150, 35);

        lblDos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDos.setText("Date of Subs :");
        getContentPane().add(lblDos);
        lblDos.setBounds(830, 200, 150, 35);

        lbln.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbln);
        lbln.setBounds(430, 280, 250, 35);

        lblp.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblp);
        lblp.setBounds(1030, 300, 250, 35);

        lblg.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblg);
        lblg.setBounds(430, 360, 250, 35);

        lbla.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbla);
        lbla.setBounds(1030, 390, 250, 35);

        lble.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lble);
        lble.setBounds(430, 440, 250, 35);

        lbld.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbld.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbld);
        lbld.setBounds(1030, 210, 250, 35);

        lblCustid.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblCustid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustid.setText("Customer ID :");
        lblCustid.setPreferredSize(new java.awt.Dimension(130, 35));
        lblCustid.setRequestFocusEnabled(false);
        getContentPane().add(lblCustid);
        lblCustid.setBounds(200, 200, 150, 35);

        lbli.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbli);
        lbli.setBounds(430, 200, 250, 35);

        lblWelcome1.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome1.setText("Confirm  details");
        getContentPane().add(lblWelcome1);
        lblWelcome1.setBounds(390, 50, 510, 47);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\register.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(680, 520, 200, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\back.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 60, 80, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\background (1).jpg")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1380, 878));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1370, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void register()
    {
        Connection j = new Connection();
        DBCollection dbc = j.connection("cust");
        BasicDBObject bdb = new BasicDBObject();
        String date = lbld.getText();
        
        id = lbli.getText();
        
        bdb.put("Custid",lbli.getText());
        bdb.put("Name",lbln.getText());
        bdb.put("Pno",lblp.getText());
        bdb.put("Gender",lblg.getText());
        bdb.put("Email",lble.getText());
        bdb.put("Address",lbla.getText());
        bdb.put("Date_subs",date);
        dbc.insert(bdb);
               
        final JOptionPane jo = new JOptionPane();
        
        JOptionPane.showMessageDialog(jo,"Registered Successfully","Registration Success",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new frmDefPack(id).setVisible(true);
        
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
        register();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        this.setVisible(false);
        new frmRegister().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCustid;
    private javax.swing.JLabel lblDos;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPno;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lbla;
    private static javax.swing.JLabel lbld;
    private javax.swing.JLabel lble;
    private javax.swing.JLabel lblg;
    private javax.swing.JLabel lbli;
    private javax.swing.JLabel lbln;
    private javax.swing.JLabel lblp;
    // End of variables declaration//GEN-END:variables
}
