
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aishwariya
 */
public class frmFinalBill extends javax.swing.JFrame {

    /**
     * Creates new form frmFinalBill
     */
    String id = "";
    public frmFinalBill(String cid) {
        initComponents();
        id = cid;
        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBill = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFinalBill = new javax.swing.JTable();
        btnPDF = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        btnMail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblBill.setText("BILL");

        tblFinalBill.setBackground(new java.awt.Color(204, 204, 255));
        tblFinalBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bill ID :", null},
                {"Customer ID :", null},
                {"Customer Name :", null},
                {"Total Cost Of Packages", null},
                {"Date Of Subscription :", null}
            },
            new String [] {
                "", ""
            }
        ));
        tblFinalBill.setIntercellSpacing(new java.awt.Dimension(50, 1));
        tblFinalBill.setPreferredSize(new java.awt.Dimension(100, 250));
        tblFinalBill.setRowHeight(50);
        jScrollPane1.setViewportView(tblFinalBill);

        btnPDF.setText("Create PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnMail.setText("Send To Mail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(lblBill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(btnMail)
                        .addGap(55, 55, 55)
                        .addComponent(btnDone)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblBill)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPDF)
                    .addComponent(btnDone)
                    .addComponent(btnMail))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        
        Document doc = new Document();
         try {
            try {            
                PdfWriter.getInstance(doc, new FileOutputStream("Bill.pdf"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(frmFinalBill.class.getName()).log(Level.SEVERE, null, ex);
            }
            } 
            
          catch (DocumentException ex) {
             Logger.getLogger(frmFinalBill.class.getName()).log(Level.SEVERE, null, ex);
         }
            doc.open();
            tblFinalBill.setTableHeader(null);

            
            
            PdfPTable pdfTable = new PdfPTable(tblFinalBill.getColumnCount());

            for (int i = 0; i < tblFinalBill.getColumnCount(); i++) {
                pdfTable.addCell(tblFinalBill.getColumnName(i));
            }
            
            for (int rows = 0; rows < tblFinalBill.getRowCount(); rows++) {
                for (int cols = 0; cols < tblFinalBill.getColumnCount(); cols++) {
                    pdfTable.addCell(tblFinalBill.getModel().getValueAt(rows, cols).toString());
                }
            }
         try {
             doc.add(pdfTable);
         } catch (DocumentException ex) {
             Logger.getLogger(frmFinalBill.class.getName()).log(Level.SEVERE, null, ex);
         }
            doc.close();
         try {
             Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\Bill.pdf");
         } catch (IOException ex) {
             Logger.getLogger(frmFinalBill.class.getName()).log(Level.SEVERE, null, ex);
         }
	  System.out.println("Done");
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        
        new frmLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        Connection c = new Connection();
        DBCollection dbc = c.connection("pcust");
        DBCollection dbc1 = c.connection("cust");
        
        BasicDBObject Query = new BasicDBObject();
        Query.put("Custid", id);
        DBCursor cursor = dbc1.find(Query);
        String a = "";
        String d = "";
        
        while(cursor.hasNext()) 
        {
            DBObject obj = cursor.next();
            a = (String)obj.get("Name");
            d = (String) obj.get("Date_subs");
        }
        
        BasicDBObject Query1 = new BasicDBObject();
        Query.put("Custid", id);
        DBCursor cursor1 = dbc.find(Query1);
        String b = "";
        
        while(cursor1.hasNext()) {
            
            DBObject obj = cursor1.next();
            b = (String)obj.get("Pack_cost");
        }
        
        Random r = new Random();

        int  n = r.nextInt(100000) + 100;
        
        tblFinalBill.setValueAt(n, 0, 1);
        tblFinalBill.setValueAt(id, 1, 1);
        tblFinalBill.setValueAt(a, 2, 1);
        tblFinalBill.setValueAt(b+"/-", 3, 1);
        tblFinalBill.setValueAt(d, 4, 1);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnMail;
    private javax.swing.JButton btnPDF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBill;
    private javax.swing.JTable tblFinalBill;
    // End of variables declaration//GEN-END:variables
}
