
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


public class frmGetID extends javax.swing.JFrame {

    
    public frmGetID() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblWelcome1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot ID");
        getContentPane().setLayout(null);

        lblPhone.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhone.setText("Enter your mobile no :");
        getContentPane().add(lblPhone);
        lblPhone.setBounds(470, 230, 270, 39);

        txtPhone.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });
        getContentPane().add(txtPhone);
        txtPhone.setBounds(850, 230, 260, 35);

        lblWelcome1.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome1.setText("forgot  ID");
        getContentPane().add(lblWelcome1);
        lblWelcome1.setBounds(610, 60, 270, 47);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\next (2).png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(780, 350, 90, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\forget-password.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 120, 210, 290);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\url.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        
        next();
    }//GEN-LAST:event_txtPhoneActionPerformed

    public void next()
    {
        Connection c = new Connection();
        DBCollection dbc = c.connection("cust");
                
        String p = txtPhone.getText();
        
        BasicDBObject bdb = new BasicDBObject();
        bdb.put("Pno", p);
        DBCursor cursor = dbc.find(bdb);
              
        String c1 = "";
        
        while(cursor.hasNext())
        {
            DBObject obj = cursor.next();
            String ph = (String) obj.get("Pno");
            c1 = (String) obj.get("Custid");
        }
        int i = txtPhone.getText().length();
        JOptionPane jo = new JOptionPane();
        if(i!=10)
        {
            JOptionPane.showMessageDialog(jo,"Please enter a valid mobile no!!!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else
        {        
            if(c1=="")
            {
                JOptionPane.showMessageDialog(jo,"Not an existing user!!!","Error",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                this.setVisible(false);
                new frmDetails(c1).setVisible(true);
            }
        }
    }
    
    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        
      
    }//GEN-LAST:event_txtPhoneFocusLost

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        next();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        
        final KeyEvent k=evt;

        txtPhone.addKeyListener(new KeyAdapter()
        {

            public void keyTyped(KeyEvent e) 
            {
                  final char c=k.getKeyChar();
                  if (((c < '0') || (c > '9')) && (c != '\b')) 
                  {
                    txtPhone.setBackground(Color.red);
                    txtPhone.setEditable(false);
                  }
                  else
                  {
                      txtPhone.setEditable(true);
                      txtPhone.setBackground(Color.lightGray);
                  }
        }
        });
    }//GEN-LAST:event_txtPhoneKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGetID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGetID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGetID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGetID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGetID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
