
import com.mongodb.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class frmLogin extends javax.swing.JFrame {
    
    
    public frmLogin() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);    
        this.setLocationByPlatform(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setResizable(false);
        getContentPane().setLayout(null);

        lblId.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 102));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("LOGIN ID : ");
        getContentPane().add(lblId);
        lblId.setBounds(810, 130, 150, 50);

        lblPassword.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 102));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("PASSWORD : ");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(800, 220, 170, 50);

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Colonna MT", 1, 21)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(970, 360, 120, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\setbox.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 290, 220, 76);

        txtId.setBackground(new java.awt.Color(228, 245, 255));
        txtId.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(1010, 130, 200, 40);

        jLabel2.setFont(new java.awt.Font("Colonna MT", 3, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SKYLINE CABLE NETWORK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 100, 670, 60);

        pwdPassword.setBackground(new java.awt.Color(228, 245, 255));
        pwdPassword.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        pwdPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwdPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pwdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(pwdPassword);
        pwdPassword.setBounds(1010, 230, 200, 40);

        btnExit.setBackground(new java.awt.Color(102, 153, 255));
        btnExit.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1080, 470, 130, 40);

        btnClear.setBackground(new java.awt.Color(102, 153, 255));
        btnClear.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(850, 470, 130, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Downloads\\untitled (2).png")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 230, 240, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Downloads\\first (3).jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordActionPerformed
        
        login();
    }//GEN-LAST:event_pwdPasswordActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        txtId.setText(null);
        pwdPassword.setText(null);
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        login();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void login()
    {
         if(txtId.getText().equals("") || pwdPassword.getText().equals(""))
        {
            final JOptionPane jo = new JOptionPane();
            JOptionPane.showMessageDialog(jo,"Please fill all the fields!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try{
            String s = txtId.getText();
            String p = pwdPassword.getText();
            String id = "";
            String pwd = "";

            Connection c = new Connection();
            DBCollection dbc = c.connection("emp");

            BasicDBObject Query1 = new BasicDBObject();
            Query1.put("Username", s);
            DBCursor cursor1 = dbc.find(Query1);

            BasicDBObject Query2 = new BasicDBObject();
            Query2.put("Password", s);
            DBCursor cursor2 = dbc.find(Query2);

            while(cursor1.hasNext()) 
            {
                DBObject obj1 = cursor1.next();
                id = (String)obj1.get("Username");  
            }

            while(cursor2.hasNext()) 
            {
                DBObject obj2 = cursor2.next();
                pwd = (String)obj2.get("Password");  
            }

            final JPanel p1 = new JPanel();
            final JOptionPane jo = new JOptionPane();

            if(id.toString().equals(s) && pwd.toString().equals(p))
            {
                this.setVisible(false);
                new frmChoose().setVisible(true);
            }
            else if((s.equals("admin")) && (p.equals("pass")))
            {
                this.setVisible(false);
                new frmAdminOption().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(p1,"Incorrect Id or Password","login error",JOptionPane.ERROR_MESSAGE);
            }

            }
             catch(Exception e)
            {
                final JPanel p1 = new JPanel();
                JOptionPane.showMessageDialog(p1,"Incorrect Id or Password","login error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPasswordField pwdPassword;
    public static javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

}
