
import com.mongodb.BasicDBObject;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class frmOther extends javax.swing.JFrame {

    /**
     * Creates new form frmOther
     */
    String id = "";
    public frmOther(String a) {

        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        id = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblChannels = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        lblWelcome2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFinalChannels = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Packages");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tblChannels.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblChannels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pack ID", "Pack Name", "Channels", "Pack Cost"
            }
        ));
        tblChannels.setIntercellSpacing(new java.awt.Dimension(10, 1));
        tblChannels.setRowHeight(25);
        tblChannels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChannelsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChannels);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 150, 570, 180);

        btnAdd.setBackground(new java.awt.Color(102, 153, 255));
        btnAdd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(160, 310, 113, 40);

        btnRemove.setBackground(new java.awt.Color(102, 153, 255));
        btnRemove.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("REMOVE");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove);
        btnRemove.setBounds(160, 470, 113, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\back.png")); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 80, 90, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\next (2).jpg")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1160, 350, 100, 90);

        lblWelcome1.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome1.setText("Selected  packages");
        getContentPane().add(lblWelcome1);
        lblWelcome1.setBounds(430, 400, 510, 47);

        lblWelcome2.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome2.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        lblWelcome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome2.setText("Select  other  packages");
        getContentPane().add(lblWelcome2);
        lblWelcome2.setBounds(440, 50, 510, 47);

        tblFinalChannels.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblFinalChannels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pack ID", "Pack Name", "Channels", "Pack Cost"
            }
        ));
        tblFinalChannels.setIntercellSpacing(new java.awt.Dimension(10, 1));
        tblFinalChannels.setRowHeight(25);
        tblFinalChannels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFinalChannelsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFinalChannels);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(400, 480, 570, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\url.jpg")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 768));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        TableModel model1 = tblChannels.getModel();
        int[] index = tblChannels.getSelectedRows();
        int in = tblChannels.getSelectedRow();
        
        String ind = tblChannels.getValueAt(in,0).toString();
        int c = tblFinalChannels.getRowCount();
        boolean exist = false;
        
        Object[] row = new Object[4];
        DefaultTableModel dtm  = (DefaultTableModel) tblFinalChannels.getModel();
        
        String[] pid = new String[c];
        for(int i=0;i<c;i++)
        {
            pid[i] = tblFinalChannels.getValueAt(i,0).toString();
        }
        
        for(int j=0;j<c;j++)
        {
            if(pid[j].equals(ind))
            {
                exist = true;
            }
        }       
              
        if(exist==false)
        {
            for(int i = 0;i< index.length;i++)
            {
                row[0] = model1.getValueAt(index[i],0);
                row[1] = model1.getValueAt(index[i],1);
                row[2] = model1.getValueAt(index[i],2);
                row[3] = model1.getValueAt(index[i],3);
                dtm.addRow(row);
            }
        }
        else
        {
            JOptionPane jo = new JOptionPane();
            JOptionPane.showMessageDialog(jo,"Pack already selected!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        tblChannels.repaint();
        tblChannels.getSelectionModel().clearSelection();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblChannelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChannelsMouseClicked

    }//GEN-LAST:event_tblChannelsMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
    
        DefaultTableModel model = (DefaultTableModel)tblFinalChannels.getModel();
        
        int i = tblFinalChannels.getSelectedRow();
        
        if(i==-1)
        {
            JOptionPane jo = new JOptionPane();
            JOptionPane.showMessageDialog(jo,"No row selected!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
            model.removeRow(i);
        tblFinalChannels.getSelectionModel().clearSelection();
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tblFinalChannelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFinalChannelsMouseClicked
        
        
    }//GEN-LAST:event_tblFinalChannelsMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        Connection j = new Connection();
        DBCollection dbc = j.connection("Package");
        
        String[] colNames = {"Pack ID","Pack Name ","Channels","Pack Cost"};
        DefaultTableModel dtm = new DefaultTableModel(colNames,0);
        DBCursor cursor = dbc.find();
       
        String c1 = "";
        
        while(cursor.hasNext())
        {
            DBObject obj = cursor.next();
            String pid = (String)obj.get("Pid");
            String pname = (String)obj.get("Pack_name");
            
            BasicDBObject bdb = new BasicDBObject();
            bdb.put("Pid",pid);
            DBCursor cursor1 = dbc.find(bdb);
            while(cursor1.hasNext())
            {
                c1 = cursor1.next().get("Channels").toString();
            }
  
            String cost = (String)obj.get("Pack_cost");
            
            dtm.addRow(new Object[]{pid,pname,c1,cost});
            tblChannels.setModel(dtm);
        }
        
       
    }//GEN-LAST:event_formWindowActivated

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        this.setVisible(false);
        new frmDefPack(id).setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        int x = tblFinalChannels.getRowCount();
        if(x==0)
        {
            final JOptionPane jo = new JOptionPane();
            JOptionPane.showMessageDialog(jo,"Please select a pack!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
            Vector v = new vector();

            int s = tblFinalChannels.getRowCount();
            int t = tblFinalChannels.getSelectedRowCount();

            for (int i=0;i<s;i++)
            {
                String[] row = new String[3];
                row[0] = tblFinalChannels.getValueAt(i,0).toString();
                row[1] = tblFinalChannels.getValueAt(i,1).toString();
                row[2] = tblFinalChannels.getValueAt(i,3).toString();
                v.addElement(row);
            }
             
            new frmFinalpack(v,id).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOther.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOther.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOther.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOther.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lblWelcome2;
    private javax.swing.JTable tblChannels;
    private javax.swing.JTable tblFinalChannels;
    // End of variables declaration//GEN-END:variables

    private int tblFinalChannelsMouseClicked() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class vector extends Vector {

        public vector() {
        }
    }
}
