
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

   
public class frmRegister extends javax.swing.JFrame {

    /**
     * Creates new form frmRegister
     */
    String id = "";
     
    public frmRegister() {
        initComponents();
   
        id = UUID.randomUUID().toString().substring(0,8);
        System.out.println(id);
        setExtendedState(MAXIMIZED_BOTH);
        showDate();
        lblid.setText(id);
    }
    
    void showDate()
    {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        lblDate.setText(s.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        lblName = new javax.swing.JLabel();
        lblPno = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblDos = new javax.swing.JLabel();
        lblClear = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPno = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rdbMale = new javax.swing.JRadioButton();
        rdbFemale = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCustid = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblWelcome1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration Form");
        getContentPane().setLayout(null);

        lblName.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name: ");
        getContentPane().add(lblName);
        lblName.setBounds(190, 270, 130, 35);

        lblPno.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblPno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPno.setText("Mobile No:");
        getContentPane().add(lblPno);
        lblPno.setBounds(800, 270, 140, 35);

        lblGender.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGender.setText("Gender: ");
        getContentPane().add(lblGender);
        lblGender.setBounds(190, 360, 130, 35);

        lblEmail.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email :");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(190, 450, 130, 35);

        lblDos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDos.setText("Date of subs : ");
        getContentPane().add(lblDos);
        lblDos.setBounds(790, 180, 160, 35);

        lblClear.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\clear (3).png")); // NOI18N
        lblClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearMouseClicked(evt);
            }
        });
        getContentPane().add(lblClear);
        lblClear.setBounds(480, 560, 100, 100);

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(400, 270, 250, 35);

        txtPno.setBackground(new java.awt.Color(204, 204, 204));
        txtPno.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtPno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPnoActionPerformed(evt);
            }
        });
        txtPno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPnoFocusLost(evt);
            }
        });
        txtPno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPnoKeyPressed(evt);
            }
        });
        getContentPane().add(txtPno);
        txtPno.setBounds(1000, 270, 240, 35);

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(400, 450, 250, 35);

        rdbMale.setBackground(new java.awt.Color(204, 204, 204));
        btnGroup.add(rdbMale);
        rdbMale.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        rdbMale.setText("Male");
        rdbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rdbMale);
        rdbMale.setBounds(400, 370, 90, 30);

        rdbFemale.setBackground(new java.awt.Color(204, 204, 204));
        btnGroup.add(rdbFemale);
        rdbFemale.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        rdbFemale.setText("Female");
        getContentPane().add(rdbFemale);
        rdbFemale.setBounds(550, 370, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\cancel (3).png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(770, 560, 90, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\next (2).png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1060, 550, 100, 90);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 590, 0, 0);

        lblAddress.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress.setText("Address :");
        getContentPane().add(lblAddress);
        lblAddress.setBounds(800, 360, 130, 35);

        lblCustid.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblCustid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustid.setText("Customer ID :");
        getContentPane().add(lblCustid);
        lblCustid.setBounds(180, 180, 150, 35);

        lblDate.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblDate);
        lblDate.setBounds(1000, 180, 240, 35);

        lblid.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblid);
        lblid.setBounds(400, 180, 250, 35);

        jScrollPane1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtAddress.setRows(2);
        txtAddress.setTabSize(4);
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1000, 360, 240, 70);

        lblWelcome1.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome1.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        lblWelcome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome1.setText("Registration  form");
        getContentPane().add(lblWelcome1);
        lblWelcome1.setBounds(440, 60, 510, 47);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Neha\\Documents\\NetBeansProjects\\Cable\\background (1).jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPnoActionPerformed

    private void rdbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbMaleActionPerformed

    public void next()
    {
        final JOptionPane jo = new JOptionPane();
        int i = txtPno.getText().length();
        String emailID = txtEmail.getText();
        String emailRE = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$" ;

        Boolean flag = emailID.matches(emailRE);
       
        if(txtPno.getText().equals("") || (!rdbFemale.isSelected() && !rdbMale.isSelected()) || txtEmail.getText().equals("") || txtAddress.getText().equals(""))
        {
            JOptionPane.showMessageDialog(jo,"Please fill all the fields!!!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(i!=10)
        {
            JOptionPane.showMessageDialog(jo,"Please enter a valid mobile no!!!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!flag)
        {
            JOptionPane.showMessageDialog(jo,"Please enter a valid email ID!!!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String gender;

        if(frmRegister.rdbMale.isSelected())
            gender = frmRegister.rdbMale.getText();
        else
        {
        if(frmRegister.rdbFemale.isSelected())
            gender = frmRegister.rdbFemale.getText();
        else
            gender = null;
        }


        Vector v = new Vector();
        v.add(lblid.getText());
        v.add(txtName.getText());
        v.add(txtPno.getText());
        v.add(gender);
        v.add(txtEmail.getText());
        v.add(txtAddress.getText());
        v.add(lblDate.getText());
        new frmDisplay(v).setVisible(true);
        this.setVisible(false);
    }
    
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
      
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        
        final KeyEvent k=evt;
        
        txtName.addKeyListener(new KeyAdapter()
        {
            public void keyTyped(KeyEvent e)
            {
              final char c=k.getKeyChar();
              if(Character.isDigit(c))
              {
                  txtName.setBackground(Color.red);
                  txtName.setEditable(false);
              }
              else
              {
                  txtName.setBackground(Color.LIGHT_GRAY);;
                  txtName.setEditable(true);
              }
            }
        });
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtPnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPnoKeyPressed
        
        final KeyEvent k=evt;

        txtPno.addKeyListener(new KeyAdapter()
        {

            public void keyTyped(KeyEvent e) 
            {
                  final char c=k.getKeyChar();
                  if (((c < '0') || (c > '9')) && (c != '\b')) 
                  {
                    txtPno.setBackground(Color.red);
                    txtPno.setEditable(false);
                  }
                  else
                  {
                      txtPno.setEditable(true);
                      txtPno.setBackground(Color.lightGray);
                  }
        }
        });
    }//GEN-LAST:event_txtPnoKeyPressed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        
        JOptionPane jo = new JOptionPane();
        String emailID = txtEmail.getText();
        String emailRE = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$" ;

        Boolean flag = emailID.matches(emailRE);

        if (flag)
        {
        }
        else 
        {
            JOptionPane.showMessageDialog(jo,"Please enter a valid email ID!!!","Error",JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtPnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPnoFocusLost
        
        JOptionPane jo = new JOptionPane();
        int i = txtPno.getText().length();
        if(i!=10)
        {
            JOptionPane.showMessageDialog(jo,"Please enter a valid mobile no!!!","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtPnoFocusLost

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        next();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        txtName.setText(null);
        txtPno.setText(null);
        txtEmail.setText(null);
        rdbMale.setSelected(false);
        rdbFemale.setSelected(false);
        txtAddress.setText(null);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        this.setVisible(false);
        new frmChoose().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lblClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearMouseClicked
       
        txtName.setText(null);
        txtPno.setText(null);
        txtEmail.setText(null);
        txtAddress.setText(null);
        
    }//GEN-LAST:event_lblClearMouseClicked

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegister().setVisible(true);
            }
        });
    }


    public frmRegister(ButtonGroup btnGroup, JButton btnRegister, JDateChooser dtDos, JLabel lblDos, JLabel lblGender, JLabel lblName, JLabel lblPno, JLabel lblZip, JRadioButton rdbFemale, JRadioButton rdbMale, JTextField txtName, JTextField txtPno, JTextField txtZip) throws HeadlessException {
        this.btnGroup = btnGroup;
        this.lblDate = lblDate;
        this.lblDos = lblDos;
        this.lblGender = lblGender;
        this.lblName = lblName;
        this.lblPno = lblPno;
        this.lblEmail = lblZip;
        this.rdbFemale = rdbFemale;
        this.rdbMale = rdbMale;
        this.txtName = txtName;
        this.txtPno = txtPno;
        this.txtEmail = txtZip;
    }
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblClear;
    private javax.swing.JLabel lblCustid;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDos;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPno;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lblid;
    private static javax.swing.JRadioButton rdbFemale;
    private static javax.swing.JRadioButton rdbMale;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtName;
    public static javax.swing.JTextField txtPno;
    // End of variables declaration//GEN-END:variables
}
